[[experiments]]
experiment_name = "devtest custom test lists"
combination_generation_type = "pcg"
quit_after_n_failed_tests = 0
rcg_target_test_count = 0
retry_failed_tests_n_times = 0 
custom_test_list = [
  "600SEC_512B_1PUB_1SUB_REL_MC_0DUR_100LC",
  "600SEC_512B_1PUB_2SUB_REL_MC_1DUR_100LC",
  "600SEC_512B_2PUB_1SUB_BE_MC_2DUR_100LC",
  "600SEC_100B_1PUB_1SUB_REL_UC_3DUR_100LC",
]

  [experiments.qos_settings]
  durations_secs = []
  datalen_bytes = []
  pub_count = []
  sub_count = []
  use_reliable = []
  use_multicast = []
  durability_level = []
  latency_count = []

  [[experiments.slave_machines]]
  machine_name = "p1"
  participant_allocation = "pub"
  ip = "169.254.248.55"
  ssh_key_path = "~/.ssh/id_rsa"
  username = "acwh025"
  perftest_exec_path = "~/Documents/rtiperftest/srcCpp/objs/armv7Linux4gcc7.5.0/perftest_publisher"

  [[experiments.slave_machines]]
  machine_name = "p2" 
  participant_allocation = "sub"
  ip = "169.254.201.141"
  ssh_key_path = "~/.ssh/id_rsa"
  username = "acwh025"
  perftest_exec_path = "~/Documents/rtiperftest/srcCpp/objs/armv7Linux4gcc7.5.0/perftest_publisher"

