[[campaigns]]
campaign_name = "Devtest Self Reboot"
combination_generation_type = "rcg"
rcg_target_test_count = 10
quit_after_n_failed_tests = 10
noise_generation = {}
retry_failed_tests_n_times = 0
custom_test_list = []

  [campaigns.qos_settings]
  duration_secs = [60]
  datalen_bytes = [100]
  pub_count = [1, 5]
  sub_count = [1, 5]
  use_reliable = [true]
  use_multicast = [true]
  durability_level = [0]
  latency_count = [100]

  [[campaigns.slave_machines]]
  machine_name = "k2"
  participant_allocation = "pub"
  ip = "169.254.251.21"
  ssh_key_path = "~/.ssh/id_rsa"
  username = "acwh025"
  perftest_exec_path = "~/Documents/rtiperftest/srcCpp/objs/armv7Linux4gcc7.5.0/perftest_publisher"

  [[campaigns.slave_machines]]
  machine_name = "k3" 
  participant_allocation = "pub"
  ip = "169.254.251.22"
  ssh_key_path = "~/.ssh/id_rsa"
  username = "acwh025"
  perftest_exec_path = "~/Documents/rtiperftest/srcCpp/objs/armv7Linux4gcc7.5.0/perftest_publisher"

  [[campaigns.slave_machines]]
  machine_name = "k4" 
  participant_allocation = "sub"
  ip = "169.254.251.23"
  ssh_key_path = "~/.ssh/id_rsa"
  username = "acwh025"
  perftest_exec_path = "~/Documents/rtiperftest/srcCpp/objs/armv7Linux4gcc7.5.0/perftest_publisher"

  [[campaigns.slave_machines]]
  machine_name = "k5" 
  participant_allocation = "sub"
  ip = "169.254.251.24"
  ssh_key_path = "~/.ssh/id_rsa"
  username = "acwh025"
  perftest_exec_path = "~/Documents/rtiperftest/srcCpp/objs/armv7Linux4gcc7.5.0/perftest_publisher"
