[[campaigns]]
campaign_name = "Devtest"
gen_type = "pcg"
total_tests = 0 
max_failures = 10
max_retries = 0
test_names = []

  [campaigns.noise_gen]
  delay = {}
  bandwidth_rate = "71mbit"

  [campaigns.qos_settings]
  duration_secs = [50]
  datalen_bytes = [100]
  pub_count = [5]
  sub_count = [5]
  use_reliable = [true]
  use_multicast = [true]
  durability = [0]
  latency_count = [100]

  [[campaigns.slave_machines]]
  hostname = "vm1"
  participant_type = "pub"
  ip = "192.168.64.7"
  ssh_key_path = "~/.ssh/id_rsa"
  username = "ubuntu"
  perftest_path = "~/rtiperftest/perftest_cpp"

  [[campaigns.slave_machines]]
  hostname = "vm2" 
  participant_type = "sub"
  ip = "192.168.64.9"
  ssh_key_path = "~/.ssh/id_rsa"
  username = "ubuntu"
  perftest_path = "~/rtiperftest/perftest_cpp"
