[[campaigns]]
campaign_name = "Devtest Smart Plug Restart"
gen_type = "pcg"
total_experiments = 0
max_failures = 3
noise_gen = {}
max_retries = 3
bw_rate = ""
experiment_names = []

    [campaigns.qos_settings]
    duration_secs = [120]
    datalen_bytes = [512]
    pub_count = [1, 10]
    sub_count = [1, 10]
    use_reliable = [true, false]
    use_multicast = [true, false]
    durability = [0]
    latency_count = [100]

    [[campaigns.slave_machines]]
    hostname = "p1"
    participant_type = "pub"
    ip = "169.254.248.55"
    ssh_key_path = "~/.ssh/id_rsa"
    username = "acwh025"
    perftest_path = "~/Documents/rtiperftest/srcCpp/objs/armv7Linux4gcc7.5.0/perftest_publisher"
    smart_plug_name = "p1"
    smart_plug_ip = "192.168.1.31"
    
    [[campaigns.slave_machines]]
    hostname = "p2" 
    participant_type = "sub"
    ip = "169.254.201.141"
    ssh_key_path = "~/.ssh/id_rsa"
    username = "acwh025"
    perftest_path = "~/Documents/rtiperftest/srcCpp/objs/armv7Linux4gcc7.5.0/perftest_publisher"
    smart_plug_name = "p2"
    smart_plug_ip = "192.168.1.32"
