[[campaigns]]
campaign_name = "Multicast Exploration 512B"
gen_type = "pcg"
total_experiments = 0
max_failures = 3
max_retries = 3
restart_after_retries = 3
ping_attempts = 10
ssh_attempts = 10
experiment_names = [ "600SEC_512B_20P_10S_REL_UC_0DUR_100LC", "600SEC_512B_20P_1S_REL_UC_0DUR_100LC", "600SEC_512B_20P_5S_REL_UC_0DUR_100LC", "600SEC_512B_1P_20S_REL_MC_0DUR_100LC", "600SEC_512B_1P_20S_REL_UC_0DUR_100LC", "600SEC_512B_20P_15S_REL_MC_0DUR_100LC", "600SEC_512B_20P_20S_REL_MC_0DUR_100LC", "600SEC_512B_20P_5S_REL_MC_0DUR_100LC", "600SEC_512B_20P_1S_REL_MC_0DUR_100LC", "600SEC_512B_25P_20S_REL_UC_0DUR_100LC", "600SEC_512B_20P_15S_REL_UC_0DUR_100LC", "600SEC_512B_10P_20S_REL_UC_0DUR_100LC", "600SEC_512B_10P_20S_REL_MC_0DUR_100LC", "600SEC_512B_25P_20S_REL_MC_0DUR_100LC", "600SEC_512B_20P_25S_REL_MC_0DUR_100LC", "600SEC_512B_5P_20S_REL_UC_0DUR_100LC", "600SEC_512B_15P_20S_REL_UC_0DUR_100LC", "600SEC_512B_20P_25S_REL_UC_0DUR_100LC", "600SEC_512B_15P_20S_REL_MC_0DUR_100LC", "600SEC_512B_5P_20S_REL_MC_0DUR_100LC", "600SEC_512B_20P_20S_REL_UC_0DUR_100LC", "600SEC_512B_20P_10S_REL_MC_0DUR_100LC",]
bw_rate = ""
[[campaigns.slave_machines]]
hostname = "p1"
participant_type = "pub"
ip = "169.254.248.55"
ssh_key_path = "~/.ssh/id_rsa"
username = "acwh025"
perftest_path = "~/Documents/rtiperftest/srcCpp/objs/armv7Linux4gcc7.5.0/perftest_publisher"
smart_plug_name = "p1"
smart_plug_ip = "192.168.1.31"

[[campaigns.slave_machines]]
hostname = "p2"
participant_type = "sub"
ip = "169.254.201.141"
ssh_key_path = "~/.ssh/id_rsa"
username = "acwh025"
perftest_path = "~/Documents/rtiperftest/srcCpp/objs/armv7Linux4gcc7.5.0/perftest_publisher"
smart_plug_name = "p2"
smart_plug_ip = "192.168.1.32"


[campaigns.qos_settings]
duration_secs = [ 600,]
datalen_bytes = [ 512,]
pub_count = [ 1, 5, 10, 15, 20, 25,]
sub_count = [ 1, 5, 10, 15, 20, 25,]
use_reliable = [ true,]
use_multicast = [ true, false,]
durability = [ 0,]
latency_count = [ 100,]
