[[campaigns]]
campaign_name = "Over 64KB"
gen_type = "pcg"
total_experiments = 0
max_failures = 10
max_retries = 5
ping_attempts = 10
ssh_attempts = 10
experiment_names = []
bw_rate = "99mbit"

    [campaigns.qos_settings]
    duration_secs = [ 600 ]
    datalen_bytes = [ 96000, 128000 ]
    pub_count = [1, 5, 10, 15, 20]
    sub_count = [1, 5, 10, 15, 20]
    use_reliable = [ true, false ]
    use_multicast = [ true, false ]
    durability = [ 0 ]
    latency_count = [ 100 ]

    [[campaigns.slave_machines]]
    hostname = "p1"
    participant_type = "pub"
    ip = "169.254.248.55"
    ssh_key_path = "~/.ssh/id_rsa"
    username = "acwh025"
    perftest_path = "~/Documents/rtiperftest/srcCpp/objs/armv7Linux4gcc7.5.0/perftest_publisher"
    smart_plug_name = "p1"
    smart_plug_ip = "192.168.1.31"

    [[campaigns.slave_machines]]
    hostname = "p2"
    participant_type = "sub"
    ip = "169.254.201.141"
    ssh_key_path = "~/.ssh/id_rsa"
    username = "acwh025"
    perftest_path = "~/Documents/rtiperftest/srcCpp/objs/armv7Linux4gcc7.5.0/perftest_publisher"
    smart_plug_name = "p2"
    smart_plug_ip = "192.168.1.32"
