[[campaigns]]
campaign_name = "Over 64KB 1min"
gen_type = "pcg"
total_experiments = 0
max_failures = 10
max_retries = 10
restart_after_retries = 3
ping_attempts = 5
ssh_attempts = 5
experiment_names = []
bw_rate = ""

    [campaigns.qos_settings]
    duration_secs = [ 60 ]
    # 64K, 256K, 512K, 1M, 32M, 64M, 128M, 256M, 512M, 1G
    datalen_bytes = [ 64000, 256000, 512000, 1000000, 32000000, 64000000, 128000000, 256000000, 512000000, 1000000000 ]
    pub_count = [1]
    sub_count = [1]
    use_reliable = [ true, false ]
    use_multicast = [ true, false ]
    durability = [ 0 ]
    latency_count = [ 100 ]

    [[campaigns.slave_machines]]
    hostname = "k2"
    participant_type = "pub"
    ip = "169.254.251.21"
    ssh_key_path = "~/.ssh/id_rsa"
    username = "acwh025"
    perftest_path = "~/Documents/rtiperftest/srcCpp/objs/armv7Linux4gcc7.5.0/perftest_publisher"
    smart_plug_name = "k2"
    smart_plug_ip = "192.168.1.52"

    [[campaigns.slave_machines]]
    hostname = "k3" 
    participant_type = "pub"
    ip = "169.254.251.22"
    ssh_key_path = "~/.ssh/id_rsa"
    username = "acwh025"
    perftest_path = "~/Documents/rtiperftest/srcCpp/objs/armv7Linux4gcc7.5.0/perftest_publisher"
    smart_plug_name = "k3"
    smart_plug_ip = "192.168.1.53"

    [[campaigns.slave_machines]]
    hostname = "k4" 
    participant_type = "sub"
    ip = "169.254.251.23"
    ssh_key_path = "~/.ssh/id_rsa"
    username = "acwh025"
    perftest_path = "~/Documents/rtiperftest/srcCpp/objs/armv7Linux4gcc7.5.0/perftest_publisher"
    smart_plug_name = "k4"
    smart_plug_ip = "192.168.1.54"

    [[campaigns.slave_machines]]
    hostname = "k5" 
    participant_type = "sub"
    ip = "169.254.251.24"
    ssh_key_path = "~/.ssh/id_rsa"
    username = "acwh025"
    perftest_path = "~/Documents/rtiperftest/srcCpp/objs/armv7Linux4gcc7.5.0/perftest_publisher"
    smart_plug_name = "k5"
    smart_plug_ip = "192.168.1.55"

[[campaigns]]
campaign_name = "Over 64KB 10min"
gen_type = "pcg"
total_experiments = 0
max_failures = 10
max_retries = 11
restart_after_retries = 3
ping_attempts = 5
ssh_attempts = 5
experiment_names = []
bw_rate = ""

    [campaigns.qos_settings]
    duration_secs = [ 600 ]
    # 64K, 256K, 512K, 1M, 32M, 64M, 128M, 256M, 512M, 1G
    datalen_bytes = [ 64000, 256000, 512000, 1000000, 32000000, 64000000, 128000000, 256000000, 512000000, 1000000000 ]
    pub_count = [1]
    sub_count = [1]
    use_reliable = [ true, false ]
    use_multicast = [ true, false ]
    durability = [ 0 ]
    latency_count = [ 100 ]

    [[campaigns.slave_machines]]
    hostname = "k2"
    participant_type = "pub"
    ip = "169.254.251.21"
    ssh_key_path = "~/.ssh/id_rsa"
    username = "acwh025"
    perftest_path = "~/Documents/rtiperftest/srcCpp/objs/armv7Linux4gcc7.5.0/perftest_publisher"
    smart_plug_name = "k2"
    smart_plug_ip = "192.168.1.52"

    [[campaigns.slave_machines]]
    hostname = "k3" 
    participant_type = "pub"
    ip = "169.254.251.22"
    ssh_key_path = "~/.ssh/id_rsa"
    username = "acwh025"
    perftest_path = "~/Documents/rtiperftest/srcCpp/objs/armv7Linux4gcc7.5.0/perftest_publisher"
    smart_plug_name = "k3"
    smart_plug_ip = "192.168.1.53"

    [[campaigns.slave_machines]]
    hostname = "k4" 
    participant_type = "sub"
    ip = "169.254.251.23"
    ssh_key_path = "~/.ssh/id_rsa"
    username = "acwh025"
    perftest_path = "~/Documents/rtiperftest/srcCpp/objs/armv7Linux4gcc7.5.0/perftest_publisher"
    smart_plug_name = "k4"
    smart_plug_ip = "192.168.1.54"

    [[campaigns.slave_machines]]
    hostname = "k5" 
    participant_type = "sub"
    ip = "169.254.251.24"
    ssh_key_path = "~/.ssh/id_rsa"
    username = "acwh025"
    perftest_path = "~/Documents/rtiperftest/srcCpp/objs/armv7Linux4gcc7.5.0/perftest_publisher"
    smart_plug_name = "k5"
    smart_plug_ip = "192.168.1.55"
