[[campaigns]]
campaign_name = "Devtest Smart Plug"
gen_type = "pcg"
total_experiments = 0
max_failures = 3
max_retries = 10
restart_after_retries = 3
ping_attempts = 2
ssh_attempts = 2
experiment_names = []
bw_rate = ""

    [campaigns.qos_settings]
    duration_secs = [3]
    datalen_bytes = [100]
    pub_count = [1, 2]
    sub_count = [1, 2]
    use_reliable = [true]
    use_multicast = [true]
    durability = [0]
    latency_count = [100]

    [[campaigns.slave_machines]]
    hostname = "vm1"
    participant_type = "pub"
    ip = "192.168.64.7"
    ssh_key_path = "~/.ssh/id_rsa"
    username = "ubuntu"
    perftest_path = "~/rtiperftest/perftest_cpp"

    [[campaigns.slave_machines]]
    hostname = "vm2" 
    participant_type = "sub"
    ip = "192.168.64.9"
    ssh_key_path = "~/.ssh/id_rsa"
    username = "ubuntu"
    perftest_path = "~/rtiperftest/perftest_cpp"
