[[campaigns]]
campaign_name = "Devtest"
gen_type = "pcg"
total_experiments = 0 
max_failures = 10
noise_gen = {}
max_retries = 0
experiment_names = []

    [campaigns.qos_settings]
    duration_secs = [60]
    datalen_bytes = [100, 512]
    pub_count = [5]
    sub_count = [5]
    use_reliable = [true]
    use_multicast = [true]
    durability = [0]
    latency_count = [100]

    [[campaigns.slave_machines]]
    hostname = "vm1"
    participant_type = "pub"
    ip = "192.168.64.7"
    ssh_key_path = "~/.ssh/id_rsa"
    username = "ubuntu"
    perftest_path = "~/rtiperftest/perftest_cpp"

    [[campaigns.slave_machines]]
    hostname = "vm2" 
    participant_type = "sub"
    ip = "192.168.64.9"
    ssh_key_path = "~/.ssh/id_rsa"
    username = "ubuntu"
    perftest_path = "~/rtiperftest/perftest_cpp"
