[[machines]]
name = "5pi"
ip = "100.103.95.99"
ssh_key_path = "/Users/kaleem/.ssh/id_rsa"
username = "acwh025"
config_path = "configs/5pi/mcast_exploration.json"

[[machines]]
name = "3pi"
ip = "100.114.252.94"
ssh_key_path = "/Users/kaleem/.ssh/id_rsa"
username = "acwh025"
config_path = "configs/3pi/participant_threshold.json"
